name: Ping Supabase
on:
  schedule:
    - cron: "*/1 * * * *" # every 15 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping endpoint
        run: curl -s https://mizaat.shop
